Controllers/EquiposDeFutbolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiposDeFutbol.Models;
using MvcEquiposDeFutbol.Data;
using EquiposDeFutbol.ViewModels;
using EquiposDeFutbol.Services;
using Microsoft.AspNetCore.Authorization;

namespace EquiposDeFutbol.Controllers
{
    [Authorize]
    public class EquiposDeFutbolController : Controller
    {
        private IEquipoService _EquipoService;
        private ILigaService _LigaService;
        public EquiposDeFutbolController(IEquipoService equipoService, ILigaService ligaService)
        {
            _EquipoService = equipoService;
            _LigaService = ligaService;
        }

        // GET: EquiposDeFutbol
        public  IActionResult Index(string nameFilter)
        {
          
            var equipos = _EquipoService.GetAll(nameFilter);
            var model = new EquiposViewModel {Equipos = equipos};
            return View(model);
                          
        }

        // GET: EquiposDeFutbol/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipo = _EquipoService.GetById(id.Value);
            if (equipo == null)
            {
                return NotFound();
            }

            return View(equipo);
        }

        // GET: EquiposDeFutbol/Create
        public IActionResult Create()
        {
            var ligaList = _LigaService.GetAll();
              ViewData["LigaId"] = new SelectList(ligaList, "Id", "Nombre");
            return View();
        }

        // POST: EquiposDeFutbol/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Pais,AnioFundacion,Titulos,CantidadSocios,LigaId")] Equipo equipo)
        {
            ModelState.Remove("Liga");
            ModelState.Remove("Jugadores");

            if (ModelState.IsValid)
            {
               _EquipoService.Create(equipo);
                return RedirectToAction(nameof(Index));


            }
            var ligaList = _LigaService.GetAll();
         ViewData["LigaId"] = new SelectList(ligaList, "Id", "Id", equipo.LigaId);

            return View(equipo);
        }

        // GET: EquiposDeFutbol/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var equipo = _EquipoService.GetById(id.Value);
            if (equipo == null)
            {
                return NotFound();
            }
            var ligaList = _LigaService.GetAll();
            ViewData["LigaId"] = new SelectList(ligaList, "Id", "Nombre");


            return View(equipo);
        }

        // POST: EquiposDeFutbol/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Pais,AnioFundacion,Titulos,CantidadSocios,LigaId")] Equipo equipo)
        {
            if (id != equipo.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Liga");
            ModelState.Remove("Jugadores");


            if (ModelState.IsValid)
            {
                try
                {
                    _EquipoService.Update(equipo);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipoExists(equipo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var ligaList = _LigaService.GetAll();
            ViewData["LigaId"] = new SelectList(ligaList, "Id", "Nombre");
            return View(equipo);
        }

        // GET: EquiposDeFutbol/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var equipo = _EquipoService.GetById(id.Value);
            if (equipo == null)
            {
                return NotFound();
            }

            return View(equipo);
        }

        // POST: EquiposDeFutbol/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           
            _EquipoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool EquipoExists(int id)
        {
          return  _EquipoService.GetById(id) != null;
        }
    }
}

Views/EquiposDeFutbol/Create.cshtml
@model EquiposDeFutbol.Models.Equipo

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar Equipo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label">Pais:</label>
                <input asp-for="Pais" type="text"  class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnioFundacion" class="control-label">Año de fundación:</label>
                <input asp-for="AnioFundacion" class="form-control" />
                <span asp-validation-for="AnioFundacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulos" class="control-label">Titulos:</label>
                <input asp-for="Titulos" class="form-control" min="0" />
                <span asp-validation-for="Titulos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadSocios" class="control-label">Cantidad de socios:</label>
                <input asp-for="CantidadSocios" class="form-control" />
                <span asp-validation-for="CantidadSocios" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LigaId" class="control-label">Liga:</label>
                <select asp-for="LigaId" class ="form-control" asp-items="ViewBag.LigaId">
                     <option value="">Seleccione una liga</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear Equipo" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


<button type="button" class="btn btn-dark mb-2 mt-2">
    <a asp-action="Index" class="text-light">Volver al listado</a>
</button>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EquiposDeFutbol/Delete.cshtml
@model EquiposDeFutbol.Models.Equipo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnioFundacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnioFundacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadSocios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadSocios)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/EquiposDeFutbol/Details.cshtml
@model EquiposDeFutbol.Models.Equipo

@{
    ViewData["Title"] = "Details";
}

<h1 class="font-weight-bold">Detalle Equipo</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnioFundacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnioFundacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadSocios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadSocios)
        </dd>
    </dl>
</div>
<div>
  @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
        {
        <button class="btn btn-dark">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="text-light">Editar</a> 
         </button>
        }
    <button class="btn btn-dark">
    <a asp-action="Index" class="text-light">Back to List</a>
    </button>
</div>

Views/EquiposDeFutbol/Edit.cshtml
@model EquiposDeFutbol.Models.Equipo

@{
    ViewData["Title"] = "Edit";
}

<h1 class="font-weight-bold">Editar</h1>


<h4>Equipo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label">Pais:</label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnioFundacion" class="control-label">Año de fundación:</label>
                <input asp-for="AnioFundacion" class="form-control" />
                <span asp-validation-for="AnioFundacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulos" class="control-label">Titulos:</label>
                <input asp-for="Titulos" class="form-control" />
                <span asp-validation-for="Titulos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadSocios" class="control-label">Cantidad socios:</label>
                <input asp-for="CantidadSocios" class="form-control" />
                <span asp-validation-for="CantidadSocios" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LigaId" class="control-label">Liga:</label>
                <select asp-for="LigaId" class="form-control" asp-items="ViewBag.LigaId"></select>
                <span asp-validation-for="LigaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<button type="button" class="btn btn-dark mb-2 mt-2">
    <a asp-action="Index" class="text-light">Volver al listado</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EquiposDeFutbol/Index.cshtml
@using EquiposDeFutbol.ViewModels;
@model EquiposViewModel;


@{
    ViewData["Title"] = "Index";
}

<h1 class="font-weight-bold">Equipos</h1>


<div class="d-flex justify-content-between">
    @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
    {
        <button type="button" class="btn btn-dark mb-2 mt-2">
            <a asp-action="Create" class="text-light">Agregar equipo</a>
        </button>
    }

<div class="d-flex">
    <form method="get" asp-action="Index" asp-controller="EquiposDeFutbol">
        <div class="d-flex">
        <input type="text" placeholder="Filtrar por Nombre o Pais" asp-for="NameFilter" class="form-control mt-2 bg-dark text-light"/>
        <button class="btn btn-dark h-25 mt-2 ml-1" type="submit">Buscar</button>

        </div>
    </form>
    
</div>
</div>
<div style="overflow-y:auto !important; max-height:600px !important;">
<table class="table table-dark" style="position: relative;">
    <thead>
        <tr style="position:sticky; top:0;">
            <th>
                @Html.DisplayNameFor(model => model.Equipos[0].Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipos[0].Pais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipos[0].AnioFundacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipos[0].Titulos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipos[0].CantidadSocios)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Equipos[0].Liga)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Equipos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnioFundacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadSocios)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.Liga.Nombre)
            </td>
            <td>
                @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
                {
                    <button class="btn btn-outline-secondary">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="text-light">Editar</a> </button> 
                }
                <button class="btn btn-outline-secondary ml-2">
                    <a  asp-action="Details" asp-route-id="@item.Id" class="text-light"> Detalle Equipo</a>
                   
                    </button> 
                @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
                    {
                         <button class="btn btn-outline-secondary ml-2">
                         <a  asp-action="Delete" asp-route-id="@item.Id" class="text-light">Borrar</a>
                        </button>
                    }
               
            </td>
        </tr>
}
    </tbody>
</table>
</div>