Models/Liga.cs
using System.ComponentModel.DataAnnotations;


namespace EquiposDeFutbol.Models;


public class Liga {
    public int Id { get; set; }
    public string Nombre { get; set; }
    
    public string Pais { get; set; }

     public List<Equipo> Equipos { get; set; }
}

ViewModels/LigaViewModel.cs
using EquiposDeFutbol.Models;

namespace EquiposDeFutbol.ViewModels
{
    public class LigaViewModel{
        public List<Liga> Ligas {get; set;} = new List<Liga>();

        public string? NameFilter {get; set;}
    }
}

Controllers/LigaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiposDeFutbol.Models;
using MvcEquiposDeFutbol.Data;
using EquiposDeFutbol.ViewModels;
using EquiposDeFutbol.Services;
using Microsoft.AspNetCore.Authorization;

namespace EquiposDeFutbol.Controllers
{
    [Authorize]
    public class LigaController : Controller
    {
        private ILigaService _LigaService;

        public LigaController(ILigaService ligaService)
        {
            _LigaService = ligaService;
            
        }

        // GET: Liga
        public async Task<IActionResult> Index(string nameFilter)
        {
          
           var ligas = _LigaService.GetAll(nameFilter);
            var model = new LigaViewModel {Ligas = ligas};
            return View(model);
        }

        // GET: Liga/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var liga = _LigaService.GetById(id.Value);
            if (liga == null)
            {
                return NotFound();
            }

            return View(liga);
        }

        // GET: Liga/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Liga/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Pais,Equipos")] Liga liga)
        {
            ModelState.Remove("Equipos");
            if (ModelState.IsValid)
            {
                _LigaService.Create(liga);
                return RedirectToAction(nameof(Index));
            }
            return View(liga);
        }

        // GET: Liga/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var liga = _LigaService.GetById(id.Value);
            if (liga == null)
            {
                return NotFound();
            }
            return View(liga);
        }

        // POST: Liga/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Pais")] Liga liga)
        {

            if (id != liga.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Equipos");

            if (ModelState.IsValid)
            {
                try
                {
                    _LigaService.Update(liga);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LigaExists(liga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(liga);
        }

        // GET: Liga/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var liga = _LigaService.GetById(id.Value);
            if (liga == null)
            {
                return NotFound();
            }

            return View(liga);
        }

        // POST: Liga/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           
            _LigaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool LigaExists(int id)
        {
          return  _LigaService.GetById(id) != null;
        }
    }
}

Views/Liga/Create.cshtml
@model EquiposDeFutbol.Models.Liga

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Liga</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label">Pais:</label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
          <div class="form-group">
                <input type="submit" value="Crear Liga" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<button type="button" class="btn btn-dark mb-2 mt-2">
    <a asp-action="Index" class="text-light">Volver al listado</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Liga/Delete.cshtml
@model EquiposDeFutbol.Models.Liga

@{
    ViewData["Title"] = "Delete";
}

<h1 class="font-weight-bold">Eliminar Liga</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <button type="button" class="btn btn-dark mb-2 mt-2">
    <a asp-action="Index" class="text-light">Volver al listado</a>
</button>
    </form>
</div>

Views/Liga/Details.cshtml
@model EquiposDeFutbol.Models.Liga

@{
    ViewData["Title"] = "Details";
}

<h1 class="font-weight-bold">Detalle Liga</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity != null &&(User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
        {
        <button class="btn btn-dark">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="text-light">Editar</a> 
         </button>
        }
    
    <button class="btn btn-dark">
    <a asp-action="Index" class="text-light">Volver al listado</a>
    </button>
</div>

Views/Liga/Edit.cshtml
@model EquiposDeFutbol.Models.Liga

@{
    ViewData["Title"] = "Edit";
}

<h1 class="font-weight-bold">Editar</h1>

<h4>Liga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<button type="button" class="btn btn-dark mb-2 mt-2">
    <a asp-action="Index" class="text-light">Volver al listado</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Liga/Index.cshtml
@using EquiposDeFutbol.ViewModels;
@model LigaViewModel;

@{
    ViewData["Title"] = "Index";
}

<h1 class="font-weight-bold">Ligas</h1>


<div class="d-flex justify-content-between">
    @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
        {
            <button type="button" class="btn btn-dark mb-2 mt-2">
                <a asp-action="Create" class="text-light">Agregar Liga</a>
            </button>
        }

<div class="d-flex">
    <form method="get" asp-action="Index" asp-controller="Liga">
        <div class="d-flex">
        <input type="text" placeholder="Filtrar por Nombre o Pais" asp-for="NameFilter" class="form-control mt-2 bg-dark text-light"/>
        <button class="btn btn-dark h-25 mt-2 ml-1" type="submit">Buscar</button>

        </div>
    </form>
    
</div>
</div>

<div style="overflow-y:auto !important; max-height:600px !important;">
<table class="table table-dark" style="position: relative;">
    <thead>
        <tr style="position:sticky; top:0;">
            <th>
                @Html.DisplayNameFor(model => model.Ligas[0].Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ligas[0].Pais)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Ligas) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais)
            </td>
            <td>
                @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
                {
                    <button class="btn btn-outline-secondary">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="text-light">Editar</a> </button> 
                }
              
                <button class="btn btn-outline-secondary ml-2">
                    <a  asp-action="Details" asp-route-id="@item.Id" class="text-light"> Detalle Liga</a>
                   
                    </button>
                @if (User.Identity != null && (User.IsInRole("Administrador") || User.IsInRole("AdministradorJunior")))
                    {
                        <button class="btn btn-outline-secondary ml-2">
                            <a  asp-action="Delete" asp-route-id="@item.Id" class="text-light">Borrar</a>
                        </button>
                    }  
               
            </td>
        </tr>
}
    </tbody>
</table>


</div>